USE socialgarden_sow;

DELETE FROM rate_card_roles;

INSERT INTO `rate_card_roles` (`role_name`, `hourly_rate`, `is_active`, `description`) VALUES
('Account Management - (Senior Account Director)', 365.00, TRUE, 'Senior account direction and client strategy'),
('Account Management - (Account Director)', 295.00, TRUE, 'Account director level management'),
('Account Management - (Senior Account Manager)', 210.00, TRUE, 'Senior account management'),
('Account Management - (Account Manager)', 180.00, TRUE, 'Standard account management'),
('Account Management (Off)', 120.00, TRUE, 'Offshore account management support'),
('Project Management - (Account Director)', 295.00, TRUE, 'Project management at director level'),
('Project Management - (Account Manager)', 180.00, TRUE, 'Project management and coordination'),
('Project Management - (Senior Account Manager)', 210.00, TRUE, 'Senior project management'),
('Tech - Delivery - Project Coordination', 110.00, TRUE, 'Project coordination support'),
('Tech - Delivery - Project Management', 150.00, TRUE, 'Technical project management'),
('Tech - Head Of - Senior Project Management', 365.00, TRUE, 'Head of senior project management'),
('Tech - Head Of - Customer Experience Strategy', 365.00, TRUE, 'Head of customer experience'),
('Tech - Head Of - Program Strategy', 365.00, TRUE, 'Head of program strategy'),
('Tech - Head Of - System Setup', 365.00, TRUE, 'Head of system setup and architecture'),
('Tech - Sr. Architect - Approval & Testing', 365.00, TRUE, 'Senior architect approval and QA'),
('Tech - Sr. Architect - Consultancy Services', 365.00, TRUE, 'Senior architect consultancy'),
('Tech - Sr. Architect - Data Strategy', 365.00, TRUE, 'Senior architect data strategy'),
('Tech - Sr. Architect - Integration Strategy', 365.00, TRUE, 'Senior architect integration strategy'),
('Tech - Sr. Consultant - Admin Configuration', 295.00, TRUE, 'Senior consultant admin configuration'),
('Tech - Sr. Consultant - Advisory & Consultation', 295.00, TRUE, 'Senior advisory consultation'),
('Tech - Sr. Consultant - Approval & Testing', 295.00, TRUE, 'Senior consultant QA and testing'),
('Tech - Sr. Consultant - Campaign Optimisation', 295.00, TRUE, 'Senior campaign optimization'),
('Tech - Sr. Consultant - Campaign Strategy', 295.00, TRUE, 'Senior campaign strategy'),
('Tech - Sr. Consultant - Database Management', 295.00, TRUE, 'Senior database management'),
('Tech - Sr. Consultant - Reporting', 295.00, TRUE, 'Senior reporting and analytics'),
('Tech - Sr. Consultant - Services', 295.00, TRUE, 'Senior consulting services'),
('Tech - Sr. Consultant - Strategy', 295.00, TRUE, 'Senior strategic consultation'),
('Tech - Sr. Consultant - Training', 295.00, TRUE, 'Senior training and enablement'),
('Tech - Integrations', 170.00, TRUE, 'Standard integration configuration'),
('Tech - Integrations (Srn MAP)', 295.00, TRUE, 'Senior integration MAP specialist'),
('Tech - Specialist - Admin Configuration', 180.00, TRUE, 'Specialist admin configuration'),
('Tech - Specialist - Campaign Optimisation', 180.00, TRUE, 'Campaign optimization specialist'),
('Tech - Specialist - Campaign Orchestration', 180.00, TRUE, 'Campaign orchestration specialist'),
('Tech - Specialist - Database Management', 180.00, TRUE, 'Database management specialist'),
('Tech - Specialist - Email Production', 180.00, TRUE, 'Email production specialist'),
('Tech - Specialist - Integration Configuration', 180.00, TRUE, 'Integration configuration specialist'),
('Tech - Specialist - Integration Services', 190.00, TRUE, 'Integration services specialist'),
('Tech - Specialist - Lead Scoring Setup', 180.00, TRUE, 'Lead scoring setup specialist'),
('Tech - Specialist - Program Management', 180.00, TRUE, 'Program management specialist'),
('Tech - Specialist - Reporting', 180.00, TRUE, 'Reporting and analytics specialist'),
('Tech - Specialist - Services', 180.00, TRUE, 'General technical services'),
('Tech - Specialist - Testing', 180.00, TRUE, 'QA and testing specialist'),
('Tech - Specialist - Training', 180.00, TRUE, 'Training specialist'),
('Tech - Specialist - Workflows', 180.00, TRUE, 'Workflow automation specialist'),
('Tech - Keyword Research', 120.00, TRUE, 'Keyword research support'),
('Tech - Landing Page - (Offshore)', 120.00, TRUE, 'Offshore landing page development'),
('Tech - Landing Page - (Onshore)', 210.00, TRUE, 'Onshore landing page development'),
('Tech - Producer - Admin Configuration', 120.00, TRUE, 'Producer admin configuration'),
('Tech - Producer - Campaign Build', 120.00, TRUE, 'Campaign build and execution'),
('Tech - Producer - Chat Bot / Live Chat', 120.00, TRUE, 'Chatbot and live chat setup'),
('Tech - Producer - Copywriting', 120.00, TRUE, 'Producer copywriting'),
('Tech - Producer - Deployment', 120.00, TRUE, 'Deployment and go-live support'),
('Tech - Producer - Design', 120.00, TRUE, 'Producer design work'),
('Tech - Producer - Development', 120.00, TRUE, 'Producer development work'),
('Tech - Producer - Documentation Setup', 120.00, TRUE, 'Documentation creation'),
('Tech - Producer - Email Production', 120.00, TRUE, 'Email production and setup'),
('Tech - Producer - Field / Property Setup', 120.00, TRUE, 'Field and property configuration'),
('Tech - Producer - Integration Assistance', 120.00, TRUE, 'Integration support'),
('Tech - Producer - Landing Page Production', 120.00, TRUE, 'Landing page production'),
('Tech - Producer - Lead Scoring Setup', 120.00, TRUE, 'Lead scoring configuration'),
('Tech - Producer - Reporting', 120.00, TRUE, 'Reporting setup'),
('Tech - Producer - Services', 120.00, TRUE, 'General production services'),
('Tech - Producer - SMS Setup', 120.00, TRUE, 'SMS and text setup'),
('Tech - Producer - Support & Monitoring', 120.00, TRUE, 'Ongoing support and monitoring'),
('Tech - Producer - Testing', 120.00, TRUE, 'Testing and QA support'),
('Tech - Producer - Training', 120.00, TRUE, 'Training delivery and materials'),
('Tech - Producer - Web Development', 120.00, TRUE, 'Web development support'),
('Tech - Producer - Workflows', 120.00, TRUE, 'Workflow setup and automation'),
('Tech - SEO Producer', 120.00, TRUE, 'SEO production work'),
('Tech - SEO Strategy', 180.00, TRUE, 'SEO strategy and consultation'),
('Tech - Website Optimisation', 120.00, TRUE, 'Website optimization and improvement'),
('Content - Campaign Strategy (Onshore)', 180.00, TRUE, 'Onshore campaign strategy'),
('Content - Keyword Research (Offshore)', 120.00, TRUE, 'Offshore keyword research'),
('Content - Keyword Research (Onshore)', 150.00, TRUE, 'Onshore keyword research'),
('Content - Optimisation (Onshore)', 150.00, TRUE, 'Onshore content optimization'),
('Content - Reporting (Offshore)', 120.00, TRUE, 'Offshore reporting'),
('Content - Reporting (Onshore)', 150.00, TRUE, 'Onshore reporting'),
('Content - SEO Copywriting (Onshore)', 150.00, TRUE, 'Onshore SEO copywriting'),
('Content - SEO Strategy (Onshore)', 210.00, TRUE, 'Onshore SEO strategy'),
('Content - Website Optimisations (Offshore)', 120.00, TRUE, 'Offshore website optimization'),
('Copywriting (Offshore)', 120.00, TRUE, 'Offshore copywriting services'),
('Copywriting (Onshore)', 180.00, TRUE, 'Onshore copywriting services'),
('Design - Digital Asset (Offshore)', 140.00, TRUE, 'Offshore digital asset design'),
('Design - Digital Asset (Onshore)', 190.00, TRUE, 'Onshore digital asset design'),
('Design - Email (Offshore)', 120.00, TRUE, 'Offshore email design'),
('Design - Email (Onshore)', 295.00, TRUE, 'Onshore email design'),
('Design - Landing Page (Offshore)', 120.00, TRUE, 'Offshore landing page design'),
('Design - Landing Page (Onshore)', 190.00, TRUE, 'Onshore landing page design'),
('Dev (orTech) - Landing Page - (Offshore)', 120.00, TRUE, 'Offshore landing page development'),
('Dev (orTech) - Landing Page - (Onshore)', 210.00, TRUE, 'Onshore landing page development');

SELECT COUNT(*) as total_roles FROM rate_card_roles WHERE is_active = TRUE;
SELECT '✅ Official Social Garden rate card installed!' as status;

