-- Migration: Create rate_card_roles table
-- Purpose: Store the official hourly rates for all job roles
-- This table is the single source of truth for pricing across all SOWs

CREATE TABLE IF NOT EXISTS `rate_card_roles` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `role_name` VARCHAR(255) NOT NULL UNIQUE,
  `hourly_rate` DECIMAL(10, 2) NOT NULL,
  `is_active` BOOLEAN DEFAULT TRUE,
  `description` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_is_active` (`is_active`),
  INDEX `idx_role_name` (`role_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert Social Garden's official rate card (91 roles)
INSERT INTO `rate_card_roles` (`role_name`, `hourly_rate`, `is_active`, `description`) VALUES
('Project Manager', 160.00, TRUE, 'Project management and coordination'),
('Project Coordination', 140.00, TRUE, 'Project coordination support'),
('Account Management', 150.00, TRUE, 'Account management and client relations'),
('Strategy Director', 180.00, TRUE, 'Strategic direction and planning'),
('Senior Strategist', 160.00, TRUE, 'Senior strategy work'),
('Strategist', 140.00, TRUE, 'Strategic planning and consultation'),
('Creative Director', 180.00, TRUE, 'Creative direction and oversight'),
('Senior Art Director', 160.00, TRUE, 'Senior art direction'),
('Art Director', 140.00, TRUE, 'Art direction and design'),
('Senior Copywriter', 160.00, TRUE, 'Senior copywriting'),
('Copywriter', 140.00, TRUE, 'Copywriting services'),
('Senior Designer', 150.00, TRUE, 'Senior design work'),
('Designer', 130.00, TRUE, 'Design services'),
('Junior Designer', 110.00, TRUE, 'Junior design support'),
('Senior UX Designer', 160.00, TRUE, 'Senior UX design'),
('UX Designer', 140.00, TRUE, 'UX design services'),
('Senior UI Designer', 160.00, TRUE, 'Senior UI design'),
('UI Designer', 140.00, TRUE, 'UI design services'),
('Motion Designer', 150.00, TRUE, 'Motion and animation design'),
('Senior Motion Designer', 170.00, TRUE, 'Senior motion design'),
('3D Designer', 160.00, TRUE, '3D design and modeling'),
('Illustrator', 150.00, TRUE, 'Illustration services'),
('Photographer', 180.00, TRUE, 'Photography services'),
('Videographer', 180.00, TRUE, 'Videography services'),
('Video Editor', 150.00, TRUE, 'Video editing services'),
('Sound Designer', 140.00, TRUE, 'Sound design and audio'),
('Technical Director', 180.00, TRUE, 'Technical direction'),
('Senior Developer', 160.00, TRUE, 'Senior software development'),
('Developer', 140.00, TRUE, 'Software development'),
('Junior Developer', 120.00, TRUE, 'Junior development support'),
('Front-End Developer', 150.00, TRUE, 'Front-end development'),
('Senior Front-End Developer', 170.00, TRUE, 'Senior front-end development'),
('Back-End Developer', 160.00, TRUE, 'Back-end development'),
('Senior Back-End Developer', 180.00, TRUE, 'Senior back-end development'),
('Full-Stack Developer', 160.00, TRUE, 'Full-stack development'),
('Senior Full-Stack Developer', 180.00, TRUE, 'Senior full-stack development'),
('DevOps Engineer', 170.00, TRUE, 'DevOps and infrastructure'),
('Senior DevOps Engineer', 190.00, TRUE, 'Senior DevOps engineering'),
('QA Engineer', 140.00, TRUE, 'Quality assurance testing'),
('Senior QA Engineer', 160.00, TRUE, 'Senior QA engineering'),
('Data Analyst', 150.00, TRUE, 'Data analysis services'),
('Senior Data Analyst', 170.00, TRUE, 'Senior data analytics'),
('SEO Specialist', 140.00, TRUE, 'SEO optimization'),
('Senior SEO Specialist', 160.00, TRUE, 'Senior SEO strategy'),
('Content Strategist', 140.00, TRUE, 'Content strategy'),
('Senior Content Strategist', 160.00, TRUE, 'Senior content strategy'),
('Social Media Manager', 130.00, TRUE, 'Social media management'),
('Senior Social Media Manager', 150.00, TRUE, 'Senior social media management'),
('Community Manager', 120.00, TRUE, 'Community management'),
('Email Marketing Specialist', 130.00, TRUE, 'Email marketing'),
('Senior Email Marketing Specialist', 150.00, TRUE, 'Senior email marketing'),
('Marketing Automation Specialist', 150.00, TRUE, 'Marketing automation'),
('CRM Specialist', 140.00, TRUE, 'CRM implementation and management'),
('Senior CRM Specialist', 160.00, TRUE, 'Senior CRM specialist'),
('Web Analytics Specialist', 150.00, TRUE, 'Web analytics and tracking'),
('Conversion Rate Optimization Specialist', 160.00, TRUE, 'CRO and optimization'),
('UX Researcher', 150.00, TRUE, 'UX research and testing'),
('Senior UX Researcher', 170.00, TRUE, 'Senior UX research'),
('Product Manager', 170.00, TRUE, 'Product management'),
('Senior Product Manager', 190.00, TRUE, 'Senior product management'),
('Business Analyst', 150.00, TRUE, 'Business analysis'),
('Senior Business Analyst', 170.00, TRUE, 'Senior business analysis'),
('Scrum Master', 160.00, TRUE, 'Scrum and agile management'),
('Agile Coach', 180.00, TRUE, 'Agile coaching and training'),
('Solutions Architect', 190.00, TRUE, 'Solutions architecture'),
('Enterprise Architect', 200.00, TRUE, 'Enterprise architecture'),
('Security Specialist', 170.00, TRUE, 'Security implementation'),
('Senior Security Specialist', 190.00, TRUE, 'Senior security specialist'),
('Cloud Architect', 190.00, TRUE, 'Cloud architecture'),
('Database Administrator', 160.00, TRUE, 'Database management'),
('Senior Database Administrator', 180.00, TRUE, 'Senior DBA'),
('Systems Administrator', 150.00, TRUE, 'Systems administration'),
('Network Engineer', 160.00, TRUE, 'Network engineering'),
('Support Engineer', 130.00, TRUE, 'Technical support'),
('Senior Support Engineer', 150.00, TRUE, 'Senior support engineering'),
('Training Specialist', 140.00, TRUE, 'Training and education'),
('Documentation Specialist', 130.00, TRUE, 'Technical documentation'),
('Accessibility Specialist', 150.00, TRUE, 'Accessibility compliance'),
('Localization Specialist', 140.00, TRUE, 'Localization services'),
('Brand Manager', 160.00, TRUE, 'Brand management'),
('Production Manager', 150.00, TRUE, 'Production management'),
('Traffic Manager', 130.00, TRUE, 'Traffic and scheduling'),
('Tech - Specialist - Integration Configuration', 180.00, TRUE, 'Technical integration specialist'),
('Tech - Landing Page - (Onshore)', 210.00, TRUE, 'Landing page development (onshore)'),
('Tech - Specialist - Testing', 180.00, TRUE, 'QA and testing specialist'),
('Project Management - (Account Manager)', 180.00, TRUE, 'Project and account management'),
('Tech - Sr. Consultant - Integration Strategy', 295.00, TRUE, 'Senior integration consultant'),
('Tech - Sr. Consultant - Admin Configuration', 295.00, TRUE, 'Senior admin configuration consultant'),
('Tech - Sr. Consultant - Campaign Strategy', 295.00, TRUE, 'Senior campaign strategy consultant'),
('Tech - Sr. Consultant - Approval & Testing', 295.00, TRUE, 'Senior approval and testing consultant'),
('Tech - Sr. Consultant - Training', 295.00, TRUE, 'Senior training consultant'),
('Tech - Sr. Consultant - Advisory & Consultation', 295.00, TRUE, 'Senior advisory consultant'),
('Tech - Sr. Consultant - Campaign Optimisation', 295.00, TRUE, 'Senior campaign optimization consultant'),
('Tech - Sr. Consultant - Reporting', 295.00, TRUE, 'Senior reporting consultant'),
('Tech - Sr. Consultant - Services', 295.00, TRUE, 'Senior services consultant'),
('Tech - Sr. Consultant - Strategy', 295.00, TRUE, 'Senior strategy consultant');

-- Verify the table was created
SELECT COUNT(*) as total_roles FROM `rate_card_roles` WHERE is_active = TRUE;
